name: Issue labeled

on:
  issues:
    types: [labeled, unlabeled]

jobs:
    test_label:
        runs-on: ubuntu-latest
        steps:
          - name: Dump GitHub context
            env:
              GITHUB_CONTEXT: ${{ toJson(github) }}
            run: |
              echo "$GITHUB_CONTEXT"

          - name: Cat event
            run: cat $GITHUB_EVENT_PATH
