name: PR Tester

on:
    pull_request:
        types: [opened, reopened]
        branches:
            - development

jobs:
    update_draft_release:
        runs-on: ubuntu-latest
        steps:
            - run: echo Hello ${{ github.event.inputs.input }}
