name: Push Tester

on:
  push:
    branches:
      - development

env:
  NODE_VERSION: 16
  XCODE_VERSION: 14.2

jobs:
  update_draft_release:
    runs-on: ubuntu-latest

    steps:
      - run: echo ${{ env.NODE_VERSION }}
      - run: echo ${{ env.XCODE_VERSION }}

