name: Push Tester

on:
  push:
    branches:
      - development

env:
  NODE_VERSION: 16
  XCODE_VERSION: 14.2
  DEVELOPER_DIR: /Applications/Xcode_$XCODE_VERSION.app/Contents/Developer

jobs:
  update_draft_release:
    runs-on: ubuntu-latest

    steps:
      - run: echo $NODE_VERSION
      - run: echo $XCODE_VERSION
      - run: echo $DEVELOPER_DIR
