name: Push Tester

on:
  push:
    branches:
      - development

env:
  NODE_VERSION: 16
  XCODE_VERSION: 14.2

jobs:
  update_draft_release:
    runs-on: ubuntu-latest

    env:
      DEVELOPER_DIR: /Applications/Xcode_${{XCODE_VERSION}}.app/Contents/Developer

    steps:
      - run: echo $NODE_VERSION
      - run: echo $XCODE_VERSION
      - run: echo $DEVELOPER_DIR
