name: Push Tester

on:
  push:
    branches:
      - development

env:
  NODE_VERSION: 16

jobs:
  update_draft_release:
    runs-on: ubuntu-latest

    env:
      XCODE_VERSION: 14.2
      DEVELOPER_DIR: /Applications/Xcode_14.2.app/Contents/Developer
    steps:
      - run: |
          echo ${{ env.NODE_VERSION }}
          echo ${{ env.XCODE_VERSION }}
          echo ${{ env.DEVELOPER_DIR }}
          echo $XCODE_VERSION
          echo $DEVELOPER_DIR
          echo $NODE_VERSION

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: $NODE_VERSION
